=== Qianfugen/learnjava/day24/src/xml/pets.dtd
<!ELEMENT pets (dogs,penguins)>
<!ELEMENT dogs (dog*)>
<!ELEMENT penguins (penguin+)>
<!ELEMENT dog (name,health,love,strain?)>
<!ATTLIST dog id CDATA #REQUIRED>
<!ELEMENT penguin (name,health,love,sex)>
<!ATTLIST penguin id CDATA #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT health (#PCDATA)>
<!ELEMENT love (#PCDATA)>
<!ELEMENT strain (#PCDATA)>
<!ELEMENT sex (#PCDATA)>

=== Qianfugen/learnjava/day24/src/xml/pets2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pets SYSTEM "pets.dtd">

<pets>
	<dogs>
		<dog id="1001">
			<name>汪狗子</name>
			<health>100</health>
			<love>80</love>
			<strain>拉布拉多</strain>
		</dog>
	</dogs>
	<penguins>
		<penguin id="1002">
			<name>Q仔</name>
			<health>100</health>
			<love>80</love>
			<sex>true</sex>
		</penguin>
	</penguins>
</pets>
